-- Generated by `pnpm exec drizzle-kit generate --name initial` from
-- src/schema.ts, then hand-edited to add `IF NOT EXISTS` to every
-- CREATE TABLE / CREATE [UNIQUE] INDEX (drizzle-kit does not emit this by
-- default). This is the baseline migration and must tolerate `service_meta`
-- already existing: plan 01-01's `open-store.ts` creates it ad hoc on every
-- `openStore()` call, which runs before `applyMigrations` in the service
-- startup sequence (ADR-0018). Without `IF NOT EXISTS` here, the very first
-- service start after this migration lands would fail with
-- "table service_meta already exists". If schema.ts changes and this file
-- is regenerated, re-apply this edit.
CREATE TABLE IF NOT EXISTS `cache_index` (
	`cache_key` text PRIMARY KEY NOT NULL,
	`source` text NOT NULL,
	`fetched_at` text NOT NULL,
	`expires_at` text,
	`payload_hash` text NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `job_runs` (
	`job_run_id` text PRIMARY KEY NOT NULL,
	`job_key` text NOT NULL,
	`scheduled_for` text NOT NULL,
	`started_at` text,
	`state` text NOT NULL,
	`idempotency_key` text NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS `job_runs_idempotency_key_unique` ON `job_runs` (`idempotency_key`);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `projects` (
	`project_id` text PRIMARY KEY NOT NULL,
	`path` text NOT NULL,
	`workspace_id` text,
	`display_name` text NOT NULL,
	`registered_at` text NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS `projects_path_unique` ON `projects` (`path`);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `runs` (
	`run_id` text PRIMARY KEY NOT NULL,
	`kind` text NOT NULL,
	`project_id` text,
	`claude_session_id` text,
	`state` text NOT NULL,
	`started_at` text NOT NULL,
	`last_activity_at` text,
	`ended_at` text,
	FOREIGN KEY (`project_id`) REFERENCES `projects`(`project_id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS `runs_state_idx` ON `runs` (`state`);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `service_meta` (
	`key` text PRIMARY KEY NOT NULL,
	`value` text NOT NULL
);
