-- Generated by `pnpm exec drizzle-kit generate --name vault-notes-cache`
-- from src/schema.ts, then hand-edited exactly as 0000_initial.sql was:
-- `IF NOT EXISTS` added to the CREATE TABLE and to all three
-- CREATE [UNIQUE] INDEX statements, because drizzle-kit does not emit it.
-- The generated file was also renamed from `0001_vault-notes-cache.sql` to
-- `0001_vault_notes_cache.sql` (and its `meta/_journal.json` tag with it),
-- so every migration filename uses one separator convention.
--
-- Why `IF NOT EXISTS` matters here specifically: this is the note-metadata
-- cache (PERF-06), and the cache is deliberately DISPOSABLE — a repair or
-- rebuild pass may drop and repopulate its rows at any time, and a partly
-- set-up store may already carry the table. Applying this migration must
-- therefore never be the thing that fails a service start.
--
-- The table carries metadata only. No body, content, or excerpt column
-- appears below, and none may be added: the vault's Markdown files remain
-- the sole holder of durable note content (PRD §9.5, threat T-02-10), and
-- `vault-notes-store.test.ts` asserts that absence via PRAGMA table_info.
--
-- If schema.ts changes and this file is regenerated, re-apply these edits.
CREATE TABLE IF NOT EXISTS `vault_notes` (
	`note_id` text PRIMARY KEY NOT NULL,
	`path` text NOT NULL,
	`scope` text NOT NULL,
	`stage` text NOT NULL,
	`ai_generated` text NOT NULL,
	`claim_type` text,
	`confidence` text NOT NULL,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL,
	`content_hash` text
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS `vault_notes_path_unique` ON `vault_notes` (`path`);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS `vault_notes_scope_idx` ON `vault_notes` (`scope`);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS `vault_notes_stage_idx` ON `vault_notes` (`stage`);
