-- Generated by `pnpm exec drizzle-kit generate --name claude-sessions-usage`
-- from src/schema.ts, then hand-edited exactly as 0001_vault_notes_cache.sql
-- was: `IF NOT EXISTS` added to all nine CREATE TABLE statements and to both
-- CREATE INDEX statements, because drizzle-kit does not emit it. The
-- generated file was also renamed from `0002_claude-sessions-usage.sql` to
-- `0002_claude_sessions_usage.sql` (and its `meta/_journal.json` tag with
-- it), so every migration filename uses one separator convention.
--
-- The twenty `ALTER TABLE runs ADD ...` statements are plain, with no
-- `IF NOT EXISTS`: SQLite has no ADD COLUMN IF NOT EXISTS. They are safe
-- because `applyMigrations` runs this file exactly once, in one transaction
-- with the schema_version bump, so a store either has all of them or none.
-- Every added column is nullable: automation Runs never carry session facts,
-- and existing rows read null (D-21).
--
-- What this migration holds (D-21, D-24, D-46): session identity and
-- metadata on `runs`, manual associations, message-level usage dedup, hourly
-- token counters, the coverage ledger, transcript cursors, latest-wins
-- capacity and cost snapshots, collector settings and the analysis toggle
-- log. Counters and identifiers only. No body, content, excerpt, text,
-- markdown, prompt, message, tool_input or transcript column appears below,
-- and none may be added (D-49, threat T-05-18); `migrate.test.ts` asserts
-- that absence via PRAGMA table_info. Private absolute paths (`cwd`,
-- `worktree_root`, `transcript_path`, cursor `path`) live only in this
-- store.
--
-- Merge-order rule (D-59, PR-21): Phase 5 merges after Phase 4, whose own
-- migration is also numbered 0002. Plan 05-16 therefore deletes this file,
-- `meta/0002_snapshot.json` and this file's `meta/_journal.json` entry, and
-- regenerates the same schema as `0003_*` on top of Phase 4's migration.
-- `migrate.test.ts` derives the expected schema_version from the migration
-- file count, so it needs no edit when that happens.
--
-- If schema.ts changes and this file is regenerated, re-apply these edits.
CREATE TABLE IF NOT EXISTS `analysis_toggle_log` (
	`at` text PRIMARY KEY NOT NULL,
	`enabled` text NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `capacity_snapshots` (
	`window` text PRIMARY KEY NOT NULL,
	`used_percent` text NOT NULL,
	`resets_at` text,
	`observed_at` text NOT NULL,
	`claude_session_id` text
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `collector_settings` (
	`key` text PRIMARY KEY NOT NULL,
	`value` text NOT NULL,
	`updated_at` text NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `cost_snapshots` (
	`claude_session_id` text PRIMARY KEY NOT NULL,
	`total_cost_usd` text NOT NULL,
	`first_observed_at` text NOT NULL,
	`observed_at` text NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `coverage_days` (
	`day` text PRIMARY KEY NOT NULL,
	`recorded_at` text NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `session_overrides` (
	`claude_session_id` text PRIMARY KEY NOT NULL,
	`project_id` text NOT NULL,
	`associated_at` text NOT NULL,
	FOREIGN KEY (`project_id`) REFERENCES `projects`(`project_id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `transcript_cursors` (
	`path` text PRIMARY KEY NOT NULL,
	`inode` text NOT NULL,
	`size` integer NOT NULL,
	`offset` integer NOT NULL,
	`updated_at` text NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `usage_hourly` (
	`hour_bucket` text NOT NULL,
	`claude_session_id` text NOT NULL,
	`project_key` text NOT NULL,
	`model` text NOT NULL,
	`skill_key` text NOT NULL,
	`input` integer NOT NULL,
	`output` integer NOT NULL,
	`cache_write` integer NOT NULL,
	`cache_read` integer NOT NULL,
	PRIMARY KEY(`hour_bucket`, `claude_session_id`, `project_key`, `model`, `skill_key`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `usage_seen_messages` (
	`message_id` text PRIMARY KEY NOT NULL,
	`seen_at` text NOT NULL
);
--> statement-breakpoint
ALTER TABLE `runs` ADD `pid` integer;--> statement-breakpoint
ALTER TABLE `runs` ADD `pid_started_at` text;--> statement-breakpoint
ALTER TABLE `runs` ADD `revision` integer;--> statement-breakpoint
ALTER TABLE `runs` ADD `name` text;--> statement-breakpoint
ALTER TABLE `runs` ADD `model` text;--> statement-breakpoint
ALTER TABLE `runs` ADD `effort` text;--> statement-breakpoint
ALTER TABLE `runs` ADD `launch_source` text;--> statement-breakpoint
ALTER TABLE `runs` ADD `cwd` text;--> statement-breakpoint
ALTER TABLE `runs` ADD `worktree_root` text;--> statement-breakpoint
ALTER TABLE `runs` ADD `permission_mode` text;--> statement-breakpoint
ALTER TABLE `runs` ADD `activity` text;--> statement-breakpoint
ALTER TABLE `runs` ADD `last_error` text;--> statement-breakpoint
ALTER TABLE `runs` ADD `claude_version` text;--> statement-breakpoint
ALTER TABLE `runs` ADD `transcript_path` text;--> statement-breakpoint
ALTER TABLE `runs` ADD `link_kind` text;--> statement-breakpoint
ALTER TABLE `runs` ADD `linked_from_run_id` text;--> statement-breakpoint
ALTER TABLE `runs` ADD `subagent_active_ids` text;--> statement-breakpoint
ALTER TABLE `runs` ADD `subagent_last_type` text;--> statement-breakpoint
ALTER TABLE `runs` ADD `terminate_requested_at` text;--> statement-breakpoint
ALTER TABLE `runs` ADD `end_observed_at` text;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS `runs_claude_session_id_idx` ON `runs` (`claude_session_id`);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS `runs_pid_idx` ON `runs` (`pid`);