-- Generated by `pnpm exec drizzle-kit generate --name projects-launchers`
-- from src/schema.ts, then hand-edited exactly as 0001_vault_notes_cache.sql
-- was: `IF NOT EXISTS` added to both CREATE TABLE statements and to the
-- CREATE UNIQUE INDEX, because drizzle-kit does not emit it. The generated
-- file was also renamed from `0002_projects-launchers.sql` to
-- `0002_projects_launchers.sql` (and its `meta/_journal.json` tag with it),
-- so every migration filename uses one separator convention.
--
-- SQLite has no `ALTER TABLE ... ADD COLUMN IF NOT EXISTS`. The three
-- `ALTER TABLE projects ADD ...` statements below are therefore NOT
-- individually re-runnable; their idempotence comes from `migrate.ts`
-- instead: each migration runs in its own transaction together with the
-- `schema_version` bump, so this file is applied exactly once or not at all.
--
-- What these tables hold (D-02, D-46, PROJ-14): owner choices only — pins,
-- last-opened times, an owner-typed GitHub link, scan folders, and launcher
-- configuration (bundle IDs, an executable path, argv templates). Never a
-- rendered command line, launch stderr, a commit subject, a branch name, or
-- remote-URL userinfo.
--
-- Parallel-merge rule (D-50): Phase 4 and Phase 5 each generate a `0002_*`
-- migration on their own branch. Whichever branch merges to `main` SECOND
-- deletes its own `0002_*.sql` and `meta/0002_snapshot.json`, reverts
-- `meta/_journal.json` to the first merger's version, re-runs
-- `drizzle-kit generate` on top (producing `0003_*`), and re-applies these
-- hand edits. `migrate.test.ts` derives its expected version from the file
-- count (PR-09), so that test needs no edit.
--
-- If schema.ts changes and this file is regenerated, re-apply these edits.
CREATE TABLE IF NOT EXISTS `launcher_config` (
	`launcher_id` text PRIMARY KEY NOT NULL,
	`config_json` text NOT NULL,
	`tested` text DEFAULT 'false' NOT NULL,
	`updated_at` text NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `scan_roots` (
	`scan_root_id` text PRIMARY KEY NOT NULL,
	`path` text NOT NULL,
	`depth` text DEFAULT '1' NOT NULL,
	`added_at` text NOT NULL,
	`last_scanned_at` text
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS `scan_roots_path_unique` ON `scan_roots` (`path`);--> statement-breakpoint
ALTER TABLE `projects` ADD `pinned` text DEFAULT 'false' NOT NULL;--> statement-breakpoint
ALTER TABLE `projects` ADD `last_opened_at` text;--> statement-breakpoint
ALTER TABLE `projects` ADD `github_url_override` text;
