-- Phase 5 owned (wave 4 review fix). Generated by `pnpm exec drizzle-kit
-- generate --name claude_usage_quarter_hours` from src/schema.ts in two steps
-- (add `usage_quarter_hourly`, then remove `usage_hourly`, so drizzle-kit
-- never prompts about a rename), merged into this one file and snapshot, then
-- hand-edited: `IF NOT EXISTS` on the CREATE, and the INSERT ... SELECT that
-- carries existing rows over before the DROP.
--
-- Why: usage was bucketed by UTC hour, so a local day starting at :30 or
-- :45 UTC (India, Newfoundland, Nepal, parts of Australia) lost its first
-- 30-45 minutes from every range. Every real zone offset is a multiple of
-- 15 minutes, so UTC quarter-hour buckets make local-day bounds exact.
--
-- Existing rows: an hour bucket's start is also a quarter-hour start, so
-- each row is carried over unchanged. Its tokens stay attributed to the
-- hour's first quarter (exact for whole-hour zones; in a :30/:45 zone a
-- pre-migration hour straddling local midnight still lands on one side).
-- Every aggregate is recomputable: "Delete cached usage analytics" plus a
-- rescan rebuilds exact quarter-hour buckets from retained transcripts.
-- Counters and identifiers only; no content column (D-49).
--
-- Merge-order rule (D-59, PR-21): this file, like 0002_claude_sessions_usage,
-- is Phase 5 schema. Plan 05-16 renumbers every Phase 5 migration after
-- Phase 4's on merge: keep this file (with its data-carrying INSERT) as its
-- own migration, ordered after the regenerated Phase 5 base migration, and
-- re-point its meta snapshot's prevId. Do not fold it into a regenerated
-- base migration, or stores already at this version would skip the carry-over.
CREATE TABLE IF NOT EXISTS `usage_quarter_hourly` (
	`bucket_start` text NOT NULL,
	`claude_session_id` text NOT NULL,
	`project_key` text NOT NULL,
	`model` text NOT NULL,
	`skill_key` text NOT NULL,
	`input` integer NOT NULL,
	`output` integer NOT NULL,
	`cache_write` integer NOT NULL,
	`cache_read` integer NOT NULL,
	PRIMARY KEY(`bucket_start`, `claude_session_id`, `project_key`, `model`, `skill_key`)
);
--> statement-breakpoint
INSERT INTO `usage_quarter_hourly`
	(`bucket_start`, `claude_session_id`, `project_key`, `model`, `skill_key`, `input`, `output`, `cache_write`, `cache_read`)
	SELECT `hour_bucket`, `claude_session_id`, `project_key`, `model`, `skill_key`, `input`, `output`, `cache_write`, `cache_read`
	FROM `usage_hourly`;
--> statement-breakpoint
DROP TABLE `usage_hourly`;
