-- Phase 5 owned (wave 4 review fix). Generated by `pnpm exec drizzle-kit
-- generate --name claude_transcript_recognition` from src/schema.ts, then
-- hand-edited only to add `IF NOT EXISTS`, as 0001 and 0002 were.
--
-- Why: the transcript scanner's per-version recognition tallies (D-41,
-- PR-11) lived in memory only, so after a restart a format-changed period
-- read as complete. They are now persisted per parser version, the service
-- holds cursors and coverage while the verdict is unavailable, and a parser
-- version change drops the other versions' rows together with the cursors
-- and the coverage ledger. "Delete cached usage analytics" empties this
-- table too. Counters and version strings only; no content column (D-49).
--
-- Merge-order rule (D-59, PR-21): Phase 5 schema. Plan 05-16 renumbers every
-- Phase 5 migration after Phase 4's on merge; this file needs only its
-- number, its journal tag and its meta snapshot's prevId re-pointed (it
-- carries no data, so it may also be folded into a regenerated Phase 5 base
-- migration, unlike 0003_claude_usage_quarter_hours).
CREATE TABLE IF NOT EXISTS `transcript_recognition` (
	`parser_version` integer NOT NULL,
	`claude_version` text NOT NULL,
	`assistant` integer NOT NULL,
	`recognized` integer NOT NULL,
	`updated_at` text NOT NULL,
	PRIMARY KEY(`parser_version`, `claude_version`)
);
