-- Phase 5 owned (wave 4 review fix). Generated by `pnpm exec drizzle-kit
-- generate --name claude_transcript_recognition` from src/schema.ts, then
-- hand-edited only to add `IF NOT EXISTS`, as 0001 and 0002 were.
--
-- Why: the transcript scanner's per-version recognition tallies (D-41,
-- PR-11) lived in memory only, so after a restart a format-changed period
-- read as complete. They are now persisted per parser version, the service
-- holds cursors and coverage while the verdict is unavailable, and a parser
-- version change drops the other versions' rows together with the cursors
-- and the coverage ledger. "Delete cached usage analytics" empties this
-- table too. Counters and version strings only; no content column (D-49).
--
-- Numbering (D-59, PR-21): renumbered from 0004 to 0005 when Phase 5 merged on
-- top of Phase 4's 0002 (plan 05-16). It carries no data.
CREATE TABLE IF NOT EXISTS `transcript_recognition` (
	`parser_version` integer NOT NULL,
	`claude_version` text NOT NULL,
	`assistant` integer NOT NULL,
	`recognized` integer NOT NULL,
	`updated_at` text NOT NULL,
	PRIMARY KEY(`parser_version`, `claude_version`)
);
