-- Phase 5 UAT fix. Generated by `pnpm exec drizzle-kit generate --name
-- session_prompt_seen`, then hand-edited to add the backfill below.
--
-- Why: a session started but never prompted saves no conversation, so
-- `claude --resume` fails for it. `prompt_seen_at` records the first proof
-- of a turn; an ended Run without one is hidden from the dashboard. Rows
-- written before this column existed that show any activity are treated as
-- having had a conversation, so history is never hidden by the upgrade.
ALTER TABLE `runs` ADD `prompt_seen_at` text;
--> statement-breakpoint
UPDATE `runs` SET `prompt_seen_at` = `last_activity_at` WHERE `kind` = 'session' AND `last_activity_at` IS NOT NULL;
