-- Phase 6 approval engine (D-13, APPR-07, APPR-08, APPR-10). Generated by
-- `pnpm exec drizzle-kit generate --name approvals` on top of the merged
-- journal (position 0007, per 06-RECONCILE.md R-MIG), then hand-edited:
--   1. `IF NOT EXISTS` added to every CREATE TABLE, CREATE INDEX and
--      CREATE UNIQUE INDEX, because drizzle-kit does not emit it and a
--      partly set-up store must never fail a service start on this file.
--   2. The triggers at the end were written by hand. drizzle-kit emits no
--      triggers and its snapshots contain none.
--
-- REBUILD HAZARD. SQLite cannot alter many column properties in place, so a
-- LATER migration that changes `proposals` or `approval_audit` makes
-- drizzle-kit emit a `__new_` table, a copy, `DROP TABLE` and a RENAME. The
-- DROP silently deletes every trigger on the table. The author of such a
-- migration MUST recreate the triggers below in that same migration. A
-- permanent test (`approval-store.test.ts`, "survival") applies ALL
-- migrations to a fresh database, asserts every trigger name exists in
-- `sqlite_master` and that each still aborts its forbidden statement, so a
-- migration that drops them fails the build.
--
-- No column below names an always-allow, remember, persist, preference,
-- allow-all or token concept, and none may be added (APPR-05, D-18). No
-- payload body is stored in `approval_audit`; `detail` is a short code.
-- Applied files are never renumbered, renamed or edited (ADR-0018, M-1).
CREATE TABLE IF NOT EXISTS `approval_audit` (
	`seq` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`proposal_id` text NOT NULL,
	`event` text NOT NULL,
	`at` text NOT NULL,
	`decided_via` text,
	`payload_hash` text,
	`detail` text
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS `approval_audit_proposal_idx` ON `approval_audit` (`proposal_id`,`seq`);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `approval_executions` (
	`proposal_id` text NOT NULL,
	`attempt` integer NOT NULL,
	`started_at` text NOT NULL,
	`finished_at` text,
	`result_code` text,
	PRIMARY KEY(`proposal_id`, `attempt`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `diagnostic_effects` (
	`proposal_id` text PRIMARY KEY NOT NULL,
	`recorded_at` text NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `proposals` (
	`proposal_id` text PRIMARY KEY NOT NULL,
	`operation` text NOT NULL,
	`subject` text NOT NULL,
	`state` text NOT NULL,
	`requester_kind` text NOT NULL,
	`requester_label` text NOT NULL,
	`project_id` text,
	`run_id` text,
	`reason` text NOT NULL,
	`payload_json` text,
	`payload_hash` text NOT NULL,
	`dedupe_key` text NOT NULL,
	`mirror_note_id` text NOT NULL,
	`created_at` text NOT NULL,
	`expires_at` text NOT NULL,
	`approved_at` text,
	`decided_at` text,
	`decided_via` text,
	`claimed_at` text,
	`claim_facts_json` text,
	`finished_at` text,
	`attempts` integer DEFAULT 0 NOT NULL,
	`outcome_code` text,
	`outcome_note` text,
	`supersedes` text,
	`revision` integer DEFAULT 1 NOT NULL,
	CONSTRAINT "proposals_state_check" CHECK("proposals"."state" IN ('pending', 'approved', 'executing', 'executed', 'failed', 'unknown', 'denied', 'expired', 'withdrawn', 'lapsed')),
	CONSTRAINT "proposals_attempts_check" CHECK("proposals"."attempts" >= 0)
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS `proposals_pending_dedupe` ON `proposals` (`dedupe_key`) WHERE "proposals"."state" = 'pending';--> statement-breakpoint
CREATE INDEX IF NOT EXISTS `proposals_state_expires_idx` ON `proposals` (`state`,`expires_at`);
--> statement-breakpoint
-- approval_audit is append-only: no UPDATE, no DELETE, and no INSERT that
-- would replace an existing row. `INSERT OR REPLACE` and `REPLACE` delete the
-- conflicting row WITHOUT firing BEFORE DELETE triggers (recursive triggers
-- are off), so the BEFORE INSERT guard is what closes them; it also blocks the
-- upsert-update form (`ON CONFLICT(seq) DO UPDATE`).
CREATE TRIGGER IF NOT EXISTS `approval_audit_no_update` BEFORE UPDATE ON `approval_audit`
BEGIN
	SELECT RAISE(ABORT, 'approval_audit is append-only');
END;
--> statement-breakpoint
CREATE TRIGGER IF NOT EXISTS `approval_audit_no_delete` BEFORE DELETE ON `approval_audit`
BEGIN
	SELECT RAISE(ABORT, 'approval_audit is append-only');
END;
--> statement-breakpoint
CREATE TRIGGER IF NOT EXISTS `approval_audit_no_replace` BEFORE INSERT ON `approval_audit`
WHEN EXISTS (SELECT 1 FROM `approval_audit` WHERE `seq` = NEW.`seq`)
BEGIN
	SELECT RAISE(ABORT, 'approval_audit is append-only');
END;
--> statement-breakpoint
-- proposals: the state machine, enforced in SQL as well as by the store's
-- compare-and-set statements (the store is the first layer, these are the
-- second). Legal transitions come from PROPOSAL_TRANSITIONS in @ccc/domain:
--   pending   -> approved, denied, expired, withdrawn
--   approved  -> executing, lapsed
--   executing -> executed, failed, unknown
-- Every other state is terminal. `UPDATE OF` fires when the column is named in
-- the SET list, so even a no-op assignment to a guarded column is refused.
CREATE TRIGGER IF NOT EXISTS `proposals_transition_guard` BEFORE UPDATE OF `state` ON `proposals`
WHEN NOT (
	(OLD.`state` = 'pending' AND NEW.`state` IN ('approved', 'denied', 'expired', 'withdrawn'))
	OR (OLD.`state` = 'approved' AND NEW.`state` IN ('executing', 'lapsed'))
	OR (OLD.`state` = 'executing' AND NEW.`state` IN ('executed', 'failed', 'unknown'))
)
BEGIN
	SELECT RAISE(ABORT, 'illegal proposal state transition');
END;
--> statement-breakpoint
-- Everything the owner saw and the payload hash covers, plus the identifiers
-- and times a decision depends on, can never be rewritten after submit.
CREATE TRIGGER IF NOT EXISTS `proposals_identity_immutable`
BEFORE UPDATE OF `proposal_id`, `operation`, `subject`, `payload_hash`, `dedupe_key`, `expires_at`, `created_at`, `requester_kind`, `requester_label`, `project_id`, `run_id`, `reason`, `mirror_note_id`, `supersedes` ON `proposals`
BEGIN
	SELECT RAISE(ABORT, 'proposal identity columns are immutable');
END;
--> statement-breakpoint
-- The payload text can change in exactly one way: to NULL, once the proposal
-- is decided (retention, D-19). It can never change while the request is
-- pending, approved or executing, and a purged payload can never be rewritten.
CREATE TRIGGER IF NOT EXISTS `proposals_payload_purge_only` BEFORE UPDATE OF `payload_json` ON `proposals`
WHEN NEW.`payload_json` IS NOT OLD.`payload_json`
	AND (NEW.`payload_json` IS NOT NULL OR OLD.`state` IN ('pending', 'approved', 'executing'))
BEGIN
	SELECT RAISE(ABORT, 'payload may only be purged after the proposal is decided');
END;
--> statement-breakpoint
-- INSERT OR REPLACE and REPLACE delete the conflicting row without firing the
-- BEFORE DELETE trigger, so a row can only be inserted when no row has its id
-- and, if it is pending, no other pending row has its dedupe key (the partial
-- unique index is the other conflict a REPLACE would resolve by deleting).
-- The store checks for a duplicate pending request first and so never trips
-- the second branch; it is here to close the REPLACE path.
CREATE TRIGGER IF NOT EXISTS `proposals_no_replace` BEFORE INSERT ON `proposals`
WHEN EXISTS (SELECT 1 FROM `proposals` WHERE `proposal_id` = NEW.`proposal_id`)
	OR (NEW.`state` = 'pending' AND EXISTS (
		SELECT 1 FROM `proposals` WHERE `state` = 'pending' AND `dedupe_key` = NEW.`dedupe_key`
	))
BEGIN
	SELECT RAISE(ABORT, 'proposals cannot be replaced');
END;
--> statement-breakpoint
CREATE TRIGGER IF NOT EXISTS `proposals_no_delete` BEFORE DELETE ON `proposals`
BEGIN
	SELECT RAISE(ABORT, 'proposals cannot be deleted');
END;
