-- Phase 6 disposable task index (D-32, ADR-0004, ADR-0022, TASK-05 to TASK-09).
-- Generated by `pnpm exec drizzle-kit generate --name task_index` on top of the
-- merged journal (position 0008, after 0007_approvals, per 06-RECONCILE.md
-- R-MIG), then hand-edited as 0001 and 0007 were: `IF NOT EXISTS` added to every
-- CREATE TABLE, CREATE INDEX and CREATE UNIQUE INDEX, because drizzle-kit does
-- not emit it and a partly set-up store must never fail a service start here.
--
-- The three tables are a DISPOSABLE cache of task filter keys. They hold no
-- note body, description, content or excerpt column, and none may be added:
-- the Markdown note is the sole holder of task content. The index can be
-- dropped and rebuilt from the vault at any time (`rebuildTaskIndex`).
-- `task-index-store.test.ts` asserts the absence via PRAGMA table_info.
--
-- A date-only value and an instant live in separate columns, never both (the
-- two CHECK constraints), so a later time-zone change cannot move an all-day
-- task. `dep_id` is deliberately not a foreign key: a dependency naming no
-- task row is a real state and counts as unmet.
--
-- This file does not touch `proposals` or `approval_audit`, so the approvals
-- triggers from 0007 are unaffected; the permanent survival test in
-- `approval-store.test.ts` still applies every migration, this one included.
-- Applied files are never renumbered, renamed or edited (ADR-0018, M-1).
CREATE TABLE IF NOT EXISTS `task_deps` (
	`note_id` text NOT NULL,
	`dep_id` text NOT NULL,
	PRIMARY KEY(`note_id`, `dep_id`)
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS `task_deps_dep_idx` ON `task_deps` (`dep_id`);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `task_index` (
	`note_id` text PRIMARY KEY NOT NULL,
	`path` text NOT NULL,
	`scope` text NOT NULL,
	`project_id` text,
	`title` text NOT NULL,
	`status` text NOT NULL,
	`priority` text,
	`due_date` text,
	`due_at` text,
	`sched_date` text,
	`sched_at` text,
	`due_sort` text,
	`completed_at` text,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL,
	`parent_id` text,
	`source_type` text,
	`assignee` text,
	`content_hash` text,
	`decision_outcome` text,
	`decision_at` text,
	`ai_generated` text NOT NULL,
	`claim_type` text,
	`confidence` text NOT NULL,
	CONSTRAINT "task_index_due_exclusive" CHECK(NOT ("task_index"."due_date" IS NOT NULL AND "task_index"."due_at" IS NOT NULL)),
	CONSTRAINT "task_index_sched_exclusive" CHECK(NOT ("task_index"."sched_date" IS NOT NULL AND "task_index"."sched_at" IS NOT NULL))
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS `task_index_path_unique` ON `task_index` (`path`);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS `task_scope_status_idx` ON `task_index` (`scope`,`status`);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS `task_project_status_idx` ON `task_index` (`project_id`,`status`);--> statement-breakpoint
CREATE INDEX IF NOT EXISTS `task_due_date_idx` ON `task_index` (`due_date`) WHERE "task_index"."due_date" IS NOT NULL;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS `task_due_at_idx` ON `task_index` (`due_at`) WHERE "task_index"."due_at" IS NOT NULL;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS `task_sched_date_idx` ON `task_index` (`sched_date`) WHERE "task_index"."sched_date" IS NOT NULL;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS `task_sched_at_idx` ON `task_index` (`sched_at`) WHERE "task_index"."sched_at" IS NOT NULL;--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `task_tags` (
	`note_id` text NOT NULL,
	`tag` text NOT NULL,
	PRIMARY KEY(`note_id`, `tag`)
);
