-- Phase 05.1 Codex token activity and the last rate-limit snapshot (D-15, D-24,
-- CODEX-08, CODEX-10). Generated by `pnpm exec drizzle-kit generate --name
-- codex_activity` on top of the merged journal (position 0009, after
-- 0008_task_index, per 05.1-RECONCILE.md R-MIG), then hand-edited as 0001, 0007
-- and 0008 were: `IF NOT EXISTS` added to every CREATE TABLE and CREATE INDEX,
-- because drizzle-kit does not emit it and a partly set-up store must never fail
-- a service start here.
--
-- The seven tables hold counters, hashed cursor keys, identifiers and the last
-- normalised rate-limit snapshot ONLY. No body, prompt, title, path, project name
-- or account column exists and none may be added; `migration-codex.audit.test.ts`
-- walks every column name. A cursor key is the SHA-256 hex of a rollout path
-- computed by the caller, so no path is ever stored.
--
-- Applied files are never renumbered, renamed or edited (ADR-0018, M-1).
CREATE TABLE IF NOT EXISTS `codex_coverage_days` (
	`day` text PRIMARY KEY NOT NULL,
	`recorded_at` text NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `codex_rate_limit_snapshot` (
	`id` integer PRIMARY KEY NOT NULL,
	`snapshot_json` text NOT NULL,
	`observed_at` text NOT NULL,
	CONSTRAINT "codex_rate_limit_snapshot_single_row" CHECK("codex_rate_limit_snapshot"."id" = 1)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `codex_recognition` (
	`parser_version` integer NOT NULL,
	`cli_version` text NOT NULL,
	`sessions` integer NOT NULL,
	`recognized` integer NOT NULL,
	`updated_at` text NOT NULL,
	PRIMARY KEY(`parser_version`, `cli_version`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `codex_rollout_cursors` (
	`cursor_key` text PRIMARY KEY NOT NULL,
	`inode` text NOT NULL,
	`size` integer NOT NULL,
	`offset` integer NOT NULL,
	`updated_at` text NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `codex_token_cumulative` (
	`thread_id` text PRIMARY KEY NOT NULL,
	`input` integer NOT NULL,
	`cached_input` integer NOT NULL,
	`cache_write` integer NOT NULL,
	`output` integer NOT NULL,
	`reasoning_output` integer NOT NULL,
	`total` integer NOT NULL,
	`updated_at` text NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `codex_token_deltas` (
	`thread_id` text NOT NULL,
	`bucket_start` text NOT NULL,
	`input` integer NOT NULL,
	`cached_input` integer NOT NULL,
	`cache_write` integer NOT NULL,
	`output` integer NOT NULL,
	`reasoning_output` integer NOT NULL,
	`total` integer NOT NULL,
	PRIMARY KEY(`thread_id`, `bucket_start`)
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS `codex_token_deltas_bucket_idx` ON `codex_token_deltas` (`bucket_start`);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `codex_token_turns` (
	`thread_id` text NOT NULL,
	`turn_id` text NOT NULL,
	`bucket_start` text NOT NULL,
	`input` integer NOT NULL,
	`cached_input` integer NOT NULL,
	`cache_write` integer NOT NULL,
	`output` integer NOT NULL,
	`reasoning_output` integer NOT NULL,
	`total` integer NOT NULL,
	`observed_at` text NOT NULL,
	PRIMARY KEY(`thread_id`, `turn_id`)
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS `codex_token_turns_bucket_idx` ON `codex_token_turns` (`bucket_start`);