import process from "node:process";
import esbuild from "esbuild";

const banner = `/* Claude Command Center plugin — built ${new Date().toISOString()} */`;

// Both the JS bundle and the CSS bundle are entry points in the same
// context so a single watch/rebuild cycle produces both `main.js` and
// `styles.css` at the plugin root (Obsidian's loader contract) from
// `outbase: "src"` + `outdir: "."`. Neither output is tracked — both are
// build artifacts, regenerated by every `pnpm run build`/`pnpm run dev`
// (REPO-08).
const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts", "src/styles.css"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
  ],
  format: "cjs",
  target: "es2022",
  logLevel: "info",
  sourcemap: process.argv.includes("--watch") ? "inline" : false,
  treeShaking: true,
  outdir: ".",
  outbase: "src",
  entryNames: "[name]",
  platform: "node",
});

if (process.argv.includes("--watch")) {
  await context.watch();
} else {
  await context.rebuild();
  await context.dispose();
}
