export { applyMigrations, SchemaAheadOfCodeError } from "./migrate.js";
export type { OperationalStore } from "./open-store.js";
export { openStore } from "./open-store.js";
export type {
  InsertProjectResult,
  InsertScanRootResult,
  LauncherConfigRecord,
  NewProject,
  NewScanRoot,
  ProjectRecord,
  ScanRootRecord,
  StoredLauncherId,
} from "./project-store.js";
export {
  findProjectByPath,
  findScanRootByPath,
  getLauncherConfig,
  getProject,
  getScanRoot,
  insertProject,
  insertScanRoot,
  listLauncherConfigs,
  listProjects,
  listScanRoots,
  markLauncherTested,
  ProjectStoreValidationError,
  removeProject,
  removeScanRoot,
  renameProject,
  STORED_LAUNCHER_IDS,
  saveLauncherConfig,
  setGithubUrlOverride,
  setProjectPinned,
  setScanRootDepth,
  touchLastOpened,
  touchScanned,
} from "./project-store.js";
export type { RunKind, RunRecord } from "./run-store.js";
export {
  getRun,
  InvalidRunStateError,
  insertRun,
  listAllRuns,
  listNonTerminalRuns,
  recoverRunToStale,
  updateRunState,
} from "./run-store.js";
export type {
  RegisteredProject,
  SessionRunIndex,
  SessionRunRow,
} from "./session-store.js";
export {
  findLiveRunByPid,
  findRunByIdentity,
  getSessionOverride,
  getSessionRun,
  InvalidSessionRunError,
  latestRunByPid,
  latestRunBySession,
  listConflictCandidates,
  listRegisteredProjects,
  listRevivableRuns,
  listSessionRunsForView,
  ProjectNotRegisteredError,
  rowToSessionRun,
  sessionRunIndex,
  setSessionOverride,
  upsertSessionRun,
} from "./session-store.js";
export type {
  AnalysisOffInterval,
  AnalysisToggle,
  CapacitySnapshot,
  CostSnapshot,
  CoverageDay,
  CoverageStatus,
  RecognitionTally,
  TokenActivityQuery,
  TokenActivityRows,
  TranscriptCursor,
  UsageRecordInput,
} from "./usage-store.js";
export {
  addRecognitionStats,
  analysisOffIntervals,
  appendToggleLog,
  deleteUsageAnalytics,
  getCollectorSetting,
  InvalidUsageRecordError,
  latestCapacity,
  listCostSnapshots,
  listToggleLog,
  markDayCovered,
  queryCoverage,
  queryTokenActivity,
  readCursor,
  readRecognitionStats,
  recordUsage,
  resetTranscriptScanState,
  setCollectorSetting,
  USAGE_BUCKET_MS,
  upsertCapacitySnapshot,
  upsertCostSnapshot,
  writeCursor,
} from "./usage-store.js";
export type { VaultNoteQuery, VaultNoteRecord } from "./vault-notes-store.js";
export {
  assertValidVaultNoteRecord,
  countVaultNotes,
  getVaultNote,
  InvalidVaultNoteError,
  queryVaultNotes,
  rebuildVaultNotes,
  upsertVaultNote,
} from "./vault-notes-store.js";
